version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Quito.2022

  parking:
    image: ${DOCKER_REGISTRY-}parking
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
